name: alphagenome_variant_scorer
owner: galaxy-alphagenome
description: Predict functional effects of genetic variants using AlphaGenome
long_description: |
  This tool uses Google DeepMind's AlphaGenome model to predict the functional
  effects of genetic variants including gene expression impact, splicing
  disruption, chromatin accessibility changes, and conservation scores.
categories:
  - Variant Analysis
  - Machine Learning
  - Genomics
homepage_url: https://github.com/galaxy-alphagenome/tools
remote_repository_url: https://github.com/galaxy-alphagenome/tools
type: unrestricted
auto_tool_repositories:
  name_template: "${repository_name}"
  description_template: "${repository_name}"